fix crash
```
[?] Enter course name (e.g. EECS 281) > EECS 330
[i] Course files will be saved under 'eecs330'
Traceback (most recent call last):
  File "C:\Users\pppig\leccapdl\main.py", line 178, in <module>
    downloader = LeccapDownloader(course_name)
  File "C:\Users\pppig\leccapdl\main.py", line 35, in __init__
    self.driver = webdriver.Chrome(options=chrome_options)
                  ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\pppig\scoop\apps\python\current\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: DevToolsActivePort file doesn't exist
Stacktrace:
Symbols not available. Dumping unresolved backtrace:
        0x7ffddb5d020c
        0x7ff66a7ea235
        0x7ff66a542630
        0x7ff66a2d16dd
        0x7ff66a315b1c
        0x7ff66a3110ea
        0x7ff66a30bc03
        0x7ff66a360bc2
        0x7ff66a360400
        0x7ff66a31b0ed
        0x7ff66a31bf63
        0x7ff66a815d60
        0x7ff66a80fe8a
        0x7ff66a831005
        0x7ff66a55d71e
        0x7ff66a564e1f
        0x7ff66a54b7c4
        0x7ff66a54b97f
        0x7ff66a5318e8
        0x7ffdd9c517ac
        0x7ffdd9bd15e8
        0x7ffddb50c120
```